In [2]:
#task_1
import numpy as np
try:
    n = int(input("Enter n: "))
    diag = np.arange(1,n+1,1)
    print(np.diag(diag))
except:
    print("Error")


Enter n: 5
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [5]:
#task_3
n,m,r,c = input().split()
arr = np.ones((int(n), int(m)), dtype=int)
arr[::int(r),::]=0
arr[::,::int(c)]=0
print(arr)

5 5 2 2
[[0 0 0 0 0]
 [0 1 0 1 0]
 [0 0 0 0 0]
 [0 1 0 1 0]
 [0 0 0 0 0]]


In [6]:
#task_6
arr = np.array(input().split(), dtype =int)
arr[arr!=0]=-1
print(arr)

4 2 6 0 7 0 2 4 6 0
[-1 -1 -1  0 -1  0 -1 -1 -1  0]


In [7]:
#task_7
arr = np.array(input().split(), dtype =int)
arr[arr==0]=-1
print(arr)

7 0 2 9 0 0 8
[ 7 -1  2  9 -1 -1  8]


In [8]:
#task_8
arr = np.array(input().split(), dtype =int)
print("Zeros: ", len(arr[arr==0]))
print("Non-zeros: ", len(arr[arr!=0]))

7 8 0 1 4 0 6 0
Zeros:  3
Non-zeros:  5


In [18]:
#task_14
arr = np.array([[0,1,0,1,0,1,0,1],
               [1,0,1,0,1,0,1,0]]*4)
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [23]:
#task_16
n = int(input())
arr = np.zeros((n,n), dtype=int)
arr[::,1::2]=1
print(arr)

6


array([[0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1]])

In [35]:
#task_18
n=int(input())
arr = np.arange(0,11,1)
arr[arr<(n/2)]*=-1
arr[arr>(3*n/4)]*=-1
print(arr)

10


array([  0,  -1,  -2,  -3,  -4,   5,   6,   7,  -8,  -9, -10])

In [43]:
#task_19
n = int(input())
arr = np.random.randint(0,99,n)
print("In array: ",arr)
s = set(arr)
print(len(s)," unique elements")

40
In array:  [34 70 67 93 47 32 56  1 64 86 81 57 92 95 78 51  2 76 73 45 36 11 95 12
 53 64 14 82 46 42 48 41 96 63 46 92 29 95 52 50]
35  unique elements


In [50]:
#task_22
n, m = input("Enter n m: ").split()
arr = np.random.randint(0, int(m),(int(n),int(n)))
print("initial matrix:\n ",arr)
arr[arr == np.max(arr)] = np.max(arr)*-1
print("Modified matrix\n: ", arr)

Enter n m: 3 5
initial matrix:
  [[3 0 2]
 [3 3 0]
 [2 0 1]]
Modified matrix
:  [[-3  0  2]
 [-3 -3  0]
 [ 2  0  1]]


In [86]:
#task_2
coef_matrix = np.array([[1,2,3,4],
                       [2,1,2,3],
                       [3,2,1,2],
                       [4,3,2,1]])
det = np.linalg.det(coef_matrix)
b_matrix= np.array([5,1,1,-5])
coef_matrix_1 = coef_matrix.copy()
coef_matrix_1[:, 0] =  b_matrix
det_1 = np.linalg.det(coef_matrix_1)
coef_matrix_1 = coef_matrix.copy()
coef_matrix_1[:,1] = b_matrix
det_2 = np.linalg.det(coef_matrix_1)
coef_matrix_1 = coef_matrix.copy()
coef_matrix_1[:,2] = b_matrix
det_3 = np.linalg.det(coef_matrix_1)
coef_matrix_1 = coef_matrix.copy()
coef_matrix_1[:,3] = b_matrix
det_4 = np.linalg.det(coef_matrix_1)
x_matrix = np.array([round(det_1/det),round(det_2/det),round(det_3/det),round(det_4/det)])
print(coef_matrix.dot(x_matrix))
print(np.linalg.solve(coef_matrix, b_matrix))
print("X array: ",x_matrix)


[ 5  1  1 -5]
[-2.  2. -3.  3.]
X array:  [-2  2 -3  3]


In [83]:
#task_3
A = np.array([[5,1,7],[-10,-2,1],[0,1,2]], dtype=int)
B = np.array([[2,4,1],[3,1,0],[7,2,1]], dtype=int)
2*(A-B)*(A**2+B)

array([[  162,   -30,   600],
       [-2678,   -30,     2],
       [  -98,    -6,    10]])

In [85]:
#task_4
coef_matrix = np.array([[4,-2,0],
                       [1,1,2],
                       [3,-2,0]])
b_matrix = np.array([0,2,0])
b2_matrix = np.array([[0,2,0],
                     [-2,4,-3],
                     [6,3,4]])
inverse_matrix = np.linalg.inv(coef_matrix)
x_matrix = inverse_matrix.dot(b_matrix)
print("X array: ",x_matrix)
print(np.linalg.solve(coef_matrix,b_matrix))
print(coef_matrix.dot(x_matrix))

X array:  [0. 0. 1.]
[0. 0. 1.]
[0. 2. 0.]
